import os

BOT_TOKEN = os.getenv("BOT_TOKEN")
CHANNEL_ID = "@KhabarF24"

CHECK_INTERVAL = 300

ENABLE_WORLD = True
ENABLE_IRAN = True
ENABLE_POLITICS = True
ENABLE_SPORT = True
ENABLE_ECONOMY = True
ENABLE_TECH = True

MAX_POSTS_PER_HOUR = 30
