"""
Category Keywords

کلمات کلیدی تشخیص دسته‌بندی خبر
"""

CATEGORY_KEYWORDS = {

    "politics": [
        "رئیس جمهور",
        "وزیر",
        "دولت",
        "پارلمان",
        "مجلس",
        "انتخابات",
        "دیپلماسی",
        "تحریم",
        "سیاست",
        "سفیر",
        "نخست وزیر",
        "کاخ سفید",
        "کرملین",
        "وزارت خارجه",
        "NATO",
        "United Nations",
        "Pentagon",
        "White House",
        "Kremlin",
        "President",
        "Prime Minister",
        "Government",
        "Election",
        "Parliament",
        "Diplomacy",
        "Diplomatic",
        "Sanctions",
        "Ambassador",
        "Foreign Ministry",
        "Congress",
        "Senate",
        "جنگ",
        "حمله",
        "موشک",
        "پهپاد",
        "انفجار",
        "ارتش",
        "نیروی هوایی",
        "پدافند",
        "درگیری",
        "حماس",
        "اسرائیل",
        "اوکراین",
        "روسیه",
        "Israel",
        "Ukraine",
        "Russia",
        "Missile",
        "Drone",
        "Airstrike",
        "Army",
        "Military",
        "War",
        "Ceasefire",
        "Conflict",
    ],

    "iran": [
        "ایران",
        "ایرانی",
        "تهران",
        "تهرانی",
        "اصفهان",
        "شیراز",
        "مشهد",
        "تبریز",
        "یزد",
        "کرمان",
        "اهواز",
        "قم",
        "Iran",
        "Iranian",
        "Tehran"
    ],

    "economy": [
        "دلار",
        "یورو",
        "بورس",
        "اقتصاد",
        "بانک",
        "تورم",
        "طلا",
        "نفت",
        "گاز",
        "بازار",
        "Bitcoin",
        "Cryptocurrency",
        "Oil",
        "Gold",
        "Inflation",
        "Economy",
        "Economic",
        "Stock",
        "Stock Market",
        "Bank",
        "Trade",
        "Tariff",
        "GDP",
        "Recession",
        "Investment",
        "Currency",
    ],

    "technology": [
        "هوش مصنوعی",
        "ربات",
        "فناوری",
        "اپل",
        "گوگل",
        "مایکروسافت",
        "OpenAI",
        "AI",
        "Artificial Intelligence",
        "Google",
        "Apple",
        "Microsoft",
        "Tesla",
        "SpaceX",
        "Technology",
        "Tech",
        "Software",
        "App",
        "Smartphone",
        "Startup",
        "Cybersecurity",
        "Chip",
        "Semiconductor",
    ],

    "health": [
        "سلامت",
        "بیمار",
        "پزشک",
        "دارو",
        "واکسن",
        "ویروس",
        "Hospital",
        "Health",
        "Medicine",
        "Medical",
        "COVID",
        "Doctor",
        "Physician",
        "Patient",
        "Pregnant",
        "Pregnancy",
        "Clinic",
        "Disease",
        "Vaccine",
        "Nurse",
        "Surgery",
        "Mental Health",
        "Diet",
        "Nutrition",
    ],

    "weather": [
        "هواشناسی",
        "بارندگی",
        "بارش",
        "طوفان",
        "زلزله",
        "سیل",
        "گرما",
        "سرما",
        "Weather",
        "Storm",
        "Flood",
        "Earthquake",
        "Hurricane",
        "Heatwave",
        "Drought",
        "Rainfall",
        "Snowfall",
    ],

    "sport": [
        "فوتبال",
        "بسکتبال",
        "والیبال",
        "تنیس",
        "کشتی",
        "فرمول یک",
        "المپیک",
        "ورزش",
        "Football",
        "Soccer",
        "Basketball",
        "Volleyball",
        "Tennis",
        "Olympics",
        "Sport",
        "Athlete",
        "Championship",
        "Tournament",
        "League",
    ]

}
